### ISSUE TITLE
Ref isn't needed anymore inside ContaView

### ISSUE THREAD

**Issue by the-Jinxist** [bushaHQ/Contra#1]
If we're using a ContraController to access other providers with ref, we don't need ref anymore in ContraView. We can make sure all the provider code stays within the controller.

I was just thinking..

**Comment by rexthecoder** [comment]
@the-Jinxist You have a point, but what happens incase we wanna use the same provider in other screen?

**Comment by rexthecoder** [comment]
![code](https://github.com/bushaHQ/Contra/assets/36260221/bbfc9500-f67c-4eac-b9b7-e67fb5643c76)
Yeah, if you can see it in this design, I am not using ref in the view anymore, I haven't updated the example

**Comment by the-Jinxist** [comment]
Yes. But in the example `CounterView`'s build method has `WidgetRef ref`. Can you remove it?

**Comment by rexthecoder** [comment]
Ohh, I get you now, that's a great idea :), yeah it can be removed @the-Jinxist

**Comment by rexthecoder** [comment]
```
class CounterView extends ContraView<CounterController> {
  CounterView({super.key}) : super(CounterController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Contra Example'),
      ),
      body: Center(
        child: Text("${controller.counter}"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => controller.increment(),
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

@the-Jinxist the issue has been fixed

**Comment by the-Jinxist** [comment]
Nice work boss!
